package support

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	CodeFlareSDKVersion = "0.12.0"
	RayVersion          = "2.5.0"
	RayImage            = "quay.io/project-codeflare/ray:latest-py39-cu118"
)
